name: Run Stock Analysis and Update Git

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 21 * * *" # 每天北京时间 5:10 AM 运行
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予 GITHUB_TOKEN 写入权限

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        env:
          API_KEYS_JSON: ${{ secrets.SECRET_API_KEYS }} # 传递 JSON 数组
        run: python top20.py

      - name: Make Shell Script Executable
        run: chmod +x update_git.sh

      - name: Run Shell Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: ./update_git.sh
