name: Notify Telegram of Latest Commit

on:
  schedule:
    - cron: '0 9 * * *'  # 每天午夜运行一次
  workflow_dispatch:  # 手动触发

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Commit
        id: get_commit
        run: |
          commit=$(git log -1 --pretty=format:"%h - %s")
          echo "::set-output name=commit::$commit"

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          message="Latest commit: ${{ steps.get_commit.outputs.commit }}"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d text="$message"
