name: Notify Telegram of Latest Commit

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get Latest Commit
        id: get_commit
        run: |
          commit=$(git log -1 --pretty=format:"%h - %s")
          echo "commit=$commit" >> $GITHUB_OUTPUT
          echo "commit_hash=$(git log -1 --pretty=format:"%h")" >> $GITHUB_OUTPUT
          echo "Debug: Latest commit is: $commit"

      - name: Get File Content and URL
        id: get_file
        run: |
          # 获取最新 commit 的 hash
          latest_commit=$(git rev-parse HEAD)
          
          # 检查该文件在最新 commit 中是否存在
          if git cat-file -e "${latest_commit}:top20_result.log" 2>/dev/null; then
            # 从最新 commit 中获取文件内容
            content=$(git show "${latest_commit}:top20_result.log" | head -c 1000)
            
            # 构建文件的 GitHub URL
            repo_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
            file_url="${repo_url}/blob/${latest_commit}/top20_result.log"
            
            # 将内容和URL保存到输出变量
            echo "content<<EOF" >> $GITHUB_OUTPUT
            echo "$content" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "file_url=$file_url" >> $GITHUB_OUTPUT
          else
            echo "Warning: top20_result.log not found in latest commit"
            echo "content=File not found in latest commit" >> $GITHUB_OUTPUT
            echo "file_url=Not available" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # 构建消息内容
          message="Latest commit: ${{ steps.get_commit.outputs.commit }}
          
          File URL: ${{ steps.get_file.outputs.file_url }}
          
          Content:
          ${{ steps.get_file.outputs.content }}"
          
          echo "Debug: Sending message: $message"
          
          # 使用 curl 发送消息到 Telegram
          response=$(curl -s -X POST \
            "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$TELEGRAM_CHAT_ID" \
            -d "text=$message" \
            -d "parse_mode=HTML" \
            -w "\n%{http_code}")
          
          http_code=$(echo "$response" | tail -n1)
          content=$(echo "$response" | sed '$d')
          
          echo "Debug: HTTP Status Code: $http_code"
          echo "Debug: Response: $content"
          
          if [ "$http_code" != "200" ]; then
            echo "Error sending message to Telegram"
            echo "Response: $content"
            exit 1
          fi
